controllers:
  n_joint_controller:
    type: JointPositionController
    joint_name: n_joint                # JHC - neck tilt
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 6
      init: 500
      min: 0
      max: 1000

  joint1_controller:
    type: JointPositionController
    joint_name: joint1                 # swivel
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 5
      init: 500
      min: 1000
      max: 0

  joint2_controller:
    type: JointPositionController
    joint_name: joint2                 # shoulder
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 4
      init: 500
      min: 1000
      max: 0

  joint3_controller:
    type: JointPositionController
    joint_name: joint3                 # elbow
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 3
      init: 500
      min: 1000
      max: 0

  joint4_controller:
    type: JointPositionController
    joint_name: joint4                 # wrist
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 2
      init: 500
      min: 1000
      max: 0

  r_joint_controller:
    type: JointPositionController
    joint_name: r_joint                # gripper
    joint_speed: 1.0
    port_id: 1
    servo:
      id: 1
      init: 500
      min: 1000
      max: 0

  arm_controller:
    type: JointTrajectoryActionController
    joint_trajectory_action_node:
      min_velocity: 0.1
      constraints:
        goal_time: 0.05
    joint_controllers:
      - "joint1_controller"
      - "joint2_controller"
      - "joint3_controller"
      - "joint4_controller"

  gripper_controller:
    type: JointTrajectoryActionController
    joint_trajectory_action_node:
      min_velocity: 0.1
      constraints:
        goal_time: 0.05
    joint_controllers:
      - "r_joint_controller"

serial_ports:
  - port_name: "/dev/ttyTHS1"
    port_id: 1
    baud_rate: 115200
    min_motor_id: 1
    max_motor_id: 6                      # JHC - neck also
    fake_read: true
    connected_ids: [ 1, 2, 3, 4, 5, 6 ]  # JHC - neck also
    update_rate: 15                      # JHC - 15 Hz max!
