#!/bin/bash

source $HOME/.typerc

export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

. /opt/ros/melodic/setup.bash
. $HOME/jetauto_ws/devel/setup.bash

export DISPLAY=:0.0
exec "$@"
